.\" 
.TH "ASTROCAM" "7" "March 08, 2007" "" ""
.SH "NAME"
AstroCam \- stepengine control daemon

.SH "SYNOPSIS"
\fBastrocam\fP

.SH "DESCRIPTION"
\fIAstroCam\fP is a stepengine control daemon for SMC\-800 stepmotor control cards based on parallel port access. It includes two web based interfaces (one written in PHP and another one written in Perl). It alternatively accepts direct SVR4-IPC input.

The installation procedure is described in the \fIINSTALL\fR file included in the package.

.SH "SUPPORTED SYSTEMS"
.IP "\\-" 4
Linux 2.2, 2.4 and 2.6
.IP "\\-" 4
OpenBSD
.IP "\\-" 4
NetBSD
.IP "\\-" 4
FreeBSD

.SH "WEBSITE"
\fIhttps://www.wendzel.de\fP

.SH "AUTHOR"
AstroCam is developed by Steffen Wendzel. The development started in December of 2001.

.SH "BUGS"
Please send bug reports to  \fIsteffen@wendzel.de\fP or use the
bug tracking service on our \fIsf.net\fP page:
\fIhttp://sf.net/projects/astrocam\fP

